import { ArrowDown, ArrowUpRight, BriefcaseBusiness, Building2, Gavel, Mail, MapPin, Phone, Scale, ShieldCheck, Users, Quote } from 'lucide-react'
import { SiteHeader } from '@/components/site-header'
import { ContactForm } from '@/components/contact-form'

const areas = [
  { icon: Scale, title: 'Direito Civil', text: 'Soluções precisas para contratos, responsabilidade civil e relações patrimoniais.' },
  { icon: BriefcaseBusiness, title: 'Empresarial', text: 'Estratégia jurídica para negócios que buscam crescer com segurança.' },
  { icon: Users, title: 'Família e Sucessões', text: 'Acolhimento e clareza em decisões que transformam histórias.' },
  { icon: Building2, title: 'Trabalhista', text: 'Atuação preventiva e contenciosa para relações de trabalho equilibradas.' },
  { icon: Gavel, title: 'Tributário', text: 'Planejamento e defesa para tornar suas escolhas mais eficientes.' },
  { icon: ShieldCheck, title: 'Contencioso Estratégico', text: 'Presença firme em disputas de alta complexidade e relevância.' },
]
const team = [{ name: 'Marina Almeida', role: 'Sócia-fundadora', bio: 'Direito empresarial e contratos', initials: 'MA' }, { name: 'Rafael Torres', role: 'Sócio', bio: 'Contencioso estratégico', initials: 'RT' }, { name: 'Clara Nogueira', role: 'Advogada', bio: 'Família e sucessões', initials: 'CN' }]
const articles = [{ date: '12 JUN 2024', title: 'A segurança jurídica como ativo do negócio', tag: 'Empresarial' }, { date: '28 MAI 2024', title: 'Contratos claros, relações duradouras', tag: 'Contratos' }, { date: '09 ABR 2024', title: 'Planejamento sucessório sem complicação', tag: 'Família' }]

export default function Home() {
  return <main>
    <SiteHeader />
    <section id="inicio" className="relative overflow-hidden bg-[var(--navy)] pt-[72px] text-[#f6f5f2]"><div className="mx-auto flex min-h-[650px] max-w-7xl flex-col justify-center px-5 py-20 lg:px-10"><div className="max-w-3xl reveal"><p className="mb-7 flex items-center gap-3 text-xs font-semibold uppercase tracking-[.2em] text-[#d7c39b]"><span className="h-px w-10 bg-[#d7c39b]" /> Advocacia contemporânea</p><h1 className="max-w-3xl font-serif text-5xl font-semibold leading-[.98] tracking-[-.02em] sm:text-7xl lg:text-8xl">Estratégia para decisões que <em className="font-normal text-[#d7c39b]">importam.</em></h1><p className="mt-8 max-w-xl text-base leading-7 text-[#d6dee4] sm:text-lg">Direito com profundidade, proximidade e visão de futuro. Atuamos ao lado de pessoas e empresas para construir caminhos seguros.</p><div className="mt-10 flex flex-col gap-3 sm:flex-row"><a href="#contato" className="flex items-center justify-center gap-2 bg-[#d7c39b] px-5 py-4 text-xs font-semibold uppercase tracking-[.14em] text-[var(--navy)] transition-colors hover:bg-[#f6f5f2]">Converse com nosso time <ArrowUpRight size={16} /></a><a href="#atuacao" className="flex items-center justify-center gap-2 border border-[#7890a0] px-5 py-4 text-xs font-semibold uppercase tracking-[.14em] text-[#f6f5f2] transition-colors hover:border-[#d7c39b]">Conheça nossa atuação</a></div></div><div className="mt-14 flex items-center gap-3 text-xs uppercase tracking-[.16em] text-[#a9b9c3]"><ArrowDown size={16} className="text-[#d7c39b]" /> Role para explorar</div></div><div className="pointer-events-none absolute -right-20 top-24 hidden h-[500px] w-[500px] rounded-full border border-[#536d7c]/50 lg:block" /><div className="pointer-events-none absolute -right-4 top-48 hidden h-[380px] w-[380px] rounded-full border border-[#536d7c]/30 lg:block" /></section>
    <section id="atuacao" className="bg-[#f6f5f2] px-5 py-24 lg:px-10 lg:py-32"><div className="mx-auto max-w-7xl"><div className="mb-14 flex flex-col justify-between gap-6 lg:flex-row lg:items-end"><div><p className="mb-4 text-xs font-semibold uppercase tracking-[.2em] text-[var(--gold)]">O que fazemos</p><h2 className="max-w-xl font-serif text-4xl leading-[1.05] text-[var(--navy)] sm:text-6xl">Direito pensado para a vida real.</h2></div><p className="max-w-sm text-sm leading-6 text-[var(--muted)]">Conhecimento técnico e escuta atenta para encontrar a solução certa para cada contexto.</p></div><div className="grid gap-px bg-[var(--line)] sm:grid-cols-2 lg:grid-cols-3">{areas.map(({ icon: Icon, title, text }) => <article key={title} className="group bg-[#f6f5f2] p-7 transition-colors hover:bg-[#edf0ed]"><Icon className="mb-12 text-[var(--gold)]" size={25} strokeWidth={1.4} /><h3 className="font-serif text-2xl text-[var(--navy)]">{title}</h3><p className="mt-3 text-sm leading-6 text-[var(--muted)]">{text}</p><span className="mt-7 block h-px w-0 bg-[var(--gold)] transition-all group-hover:w-12" /></article>)}</div></div></section>
    <section id="sobre" className="bg-[#e8ece9] px-5 py-24 lg:px-10 lg:py-32"><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-[.9fr_1.1fr] lg:items-center lg:gap-24"><div className="relative min-h-[390px] overflow-hidden bg-[var(--navy)] p-8"><div className="absolute right-0 top-0 size-56 border-l border-b border-[#d7c39b]/50" /><div className="absolute bottom-8 left-8 border border-[#d7c39b] p-4"><p className="font-serif text-5xl text-[#d7c39b]">18</p><p className="text-[10px] uppercase tracking-[.16em] text-[#e4e9e8]">anos de prática</p></div><div className="flex h-full items-center justify-center"><span className="font-serif text-[150px] font-semibold text-[#d7c39b]/20">A&T</span></div></div><div><p className="mb-4 text-xs font-semibold uppercase tracking-[.2em] text-[var(--gold)]">Sobre o escritório</p><h2 className="font-serif text-4xl leading-[1.05] text-[var(--navy)] sm:text-6xl">Advogar é estar presente.</h2><p className="mt-7 text-base leading-7 text-[var(--muted)]">Nascemos de uma convicção simples: a advocacia pode ser técnica sem deixar de ser humana. Em cada caso, combinamos repertório, estratégia e uma relação próxima com quem confia em nosso trabalho.</p><p className="mt-5 text-base leading-7 text-[var(--muted)]">Somos um escritório independente, com atuação nacional e olhar atento aos detalhes que fazem diferença.</p><a href="#contato" className="mt-8 inline-flex items-center gap-2 border-b border-[var(--gold)] pb-2 text-xs font-semibold uppercase tracking-[.14em] text-[var(--navy)]">Conheça nossa história <ArrowUpRight size={15} /></a></div></div></section>
    <section className="bg-[var(--navy)] px-5 py-20 text-[#f6f5f2] lg:px-10"><div className="mx-auto grid max-w-7xl gap-10 sm:grid-cols-3"><div><p className="font-serif text-5xl text-[#d7c39b]">18+</p><p className="mt-2 text-xs uppercase tracking-[.16em] text-[#a9b9c3]">anos de experiência</p></div><div><p className="font-serif text-5xl text-[#d7c39b]">1.200</p><p className="mt-2 text-xs uppercase tracking-[.16em] text-[#a9b9c3]">casos conduzidos</p></div><div><p className="font-serif text-5xl text-[#d7c39b]">97%</p><p className="mt-2 text-xs uppercase tracking-[.16em] text-[#a9b9c3]">de clientes recorrentes</p></div></div></section>
    <section id="equipe" className="px-5 py-24 lg:px-10 lg:py-32"><div className="mx-auto max-w-7xl"><div className="mb-14"><p className="mb-4 text-xs font-semibold uppercase tracking-[.2em] text-[var(--gold)]">Quem faz acontecer</p><h2 className="font-serif text-4xl text-[var(--navy)] sm:text-6xl">Pessoas antes de processos.</h2></div><div className="grid gap-8 sm:grid-cols-3">{team.map(person => <article key={person.name}><div className="flex aspect-[4/5] items-end bg-[#d9dfdc] p-5"><span className="font-serif text-8xl text-[var(--navy)]/20">{person.initials}</span></div><h3 className="mt-5 font-serif text-2xl text-[var(--navy)]">{person.name}</h3><p className="mt-1 text-xs font-semibold uppercase tracking-[.13em] text-[var(--gold)]">{person.role}</p><p className="mt-2 text-sm text-[var(--muted)]">{person.bio}</p></article>)}</div></div></section>
    <section id="artigos" className="bg-[#e8ece9] px-5 py-24 lg:px-10 lg:py-32"><div className="mx-auto max-w-7xl"><div className="mb-14 flex items-end justify-between gap-5"><div><p className="mb-4 text-xs font-semibold uppercase tracking-[.2em] text-[var(--gold)]">Perspectivas</p><h2 className="font-serif text-4xl text-[var(--navy)] sm:text-6xl">Do nosso olhar.</h2></div><a href="#contato" className="hidden items-center gap-2 text-xs font-semibold uppercase tracking-[.13em] text-[var(--navy)] sm:flex">Ver todos <ArrowUpRight size={15} /></a></div><div className="grid gap-px bg-[var(--line)] sm:grid-cols-3">{articles.map(article => <article key={article.title} className="bg-[#e8ece9] p-7"><p className="text-[10px] font-semibold uppercase tracking-[.16em] text-[var(--gold)]">{article.tag} · {article.date}</p><h3 className="mt-12 font-serif text-2xl leading-tight text-[var(--navy)]">{article.title}</h3><a href="#contato" className="mt-8 inline-flex items-center gap-2 text-xs font-semibold uppercase tracking-[.12em] text-[var(--muted)]">Ler artigo <ArrowUpRight size={14} /></a></article>)}</div></div></section>
    <section className="px-5 py-24 lg:px-10 lg:py-32"><div className="mx-auto max-w-4xl text-center"><Quote className="mx-auto text-[var(--gold)]" size={30} strokeWidth={1.2} /><blockquote className="mt-7 font-serif text-3xl leading-tight text-[var(--navy)] sm:text-5xl">“A clareza e o cuidado da equipe fizeram toda a diferença em uma decisão importante para nossa empresa.”</blockquote><p className="mt-7 text-xs font-semibold uppercase tracking-[.16em] text-[var(--muted)]">— Henrique M., CEO</p></div></section>
    <section id="contato" className="bg-[#e8ece9] px-5 py-24 lg:px-10 lg:py-32"><div className="mx-auto grid max-w-7xl gap-14 lg:grid-cols-[.8fr_1.2fr] lg:gap-24"><div><p className="mb-4 text-xs font-semibold uppercase tracking-[.2em] text-[var(--gold)]">Vamos conversar</p><h2 className="font-serif text-4xl leading-[1.05] text-[var(--navy)] sm:text-6xl">Seu próximo passo começa aqui.</h2><div className="mt-10 flex flex-col gap-5 text-sm text-[var(--muted)]"><p className="flex gap-3"><MapPin size={18} className="shrink-0 text-[var(--gold)]" />Av. Faria Lima, 1.650<br />São Paulo — SP, 01451-001</p><p className="flex items-center gap-3"><Phone size={18} className="text-[var(--gold)]" />(11) 3999-0000</p><p className="flex items-center gap-3"><Mail size={18} className="text-[var(--gold)]" />contato@almeidatorres.adv.br</p></div><div className="mt-10 overflow-hidden border border-[var(--line)]"><iframe title="Mapa do escritório Almeida e Torres" src="https://www.google.com/maps?q=Avenida%20Faria%20Lima%201650%20São%20Paulo&output=embed" className="h-44 w-full grayscale" loading="lazy" /></div></div><ContactForm /></div></section>
    <footer className="bg-[var(--navy)] px-5 py-12 text-[#f6f5f2] lg:px-10"><div className="mx-auto flex max-w-7xl flex-col gap-10"><div className="flex flex-col justify-between gap-8 sm:flex-row"><div><p className="font-serif text-2xl tracking-wide">ALMEIDA <span className="text-[#d7c39b]">&</span> TORRES</p><p className="mt-3 max-w-xs text-sm leading-6 text-[#a9b9c3]">Advocacia estratégica para decisões que importam.</p></div><div className="flex gap-3"><a href="#inicio" aria-label="Instagram" className="border border-[#536d7c] p-3"><span className="text-sm font-semibold">ig</span></a><a href="#inicio" aria-label="LinkedIn" className="border border-[#536d7c] p-3"><span className="text-sm font-semibold">in</span></a><a href="#inicio" aria-label="E-mail" className="border border-[#536d7c] p-3"><Mail size={17} /></a></div></div><div className="flex flex-col justify-between gap-5 border-t border-[#536d7c] pt-6 text-xs text-[#a9b9c3] sm:flex-row"><p>© 2024 Almeida & Torres Advocacia. Todos os direitos reservados.</p><a href="#inicio" className="hover:text-[#d7c39b]">Política de privacidade</a></div></div></footer>
    <a href="https://wa.me/5511999990000?text=Olá,%20gostaria%20de%20falar%20com%20o%20escritório." aria-label="Falar com o escritório pelo WhatsApp" className="fixed bottom-5 right-5 z-40 flex size-14 items-center justify-center rounded-full bg-[#d7c39b] text-[var(--navy)] shadow-lg transition-transform hover:scale-105"><Phone size={22} /></a>
  </main>
}
